<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Import-Libraries" data-toc-modified-id="Import-Libraries-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import Libraries</a></span></li><li><span><a href="#Load-Data" data-toc-modified-id="Load-Data-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Load Data</a></span></li><li><span><a href="#Exploratory-Data-Analysis" data-toc-modified-id="Exploratory-Data-Analysis-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Exploratory Data Analysis</a></span></li><li><span><a href="#Cleaning-Data-(Handling-missing-values)" data-toc-modified-id="Cleaning-Data-(Handling-missing-values)-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Cleaning Data (Handling missing values)</a></span></li><li><span><a href="#Cleaning-Data-(Mistake-Handling)" data-toc-modified-id="Cleaning-Data-(Mistake-Handling)-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Cleaning Data (Mistake Handling)</a></span></li><li><span><a href="#Cleaning-Data-(Outliers-Handling)" data-toc-modified-id="Cleaning-Data-(Outliers-Handling)-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Cleaning Data (Outliers Handling)</a></span></li><li><span><a href="#Preprocessing-(Data-Encoding-)" data-toc-modified-id="Preprocessing-(Data-Encoding-)-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Preprocessing (Data Encoding )</a></span></li><li><span><a href="#Preprocessing-(Feature-Selection-)" data-toc-modified-id="Preprocessing-(Feature-Selection-)-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Preprocessing (Feature Selection )</a></span></li><li><span><a href="#Preprocessing-(-Data-Splitting)" data-toc-modified-id="Preprocessing-(-Data-Splitting)-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Preprocessing ( Data Splitting)</a></span></li><li><span><a href="#Preprocessing-(Data-Scaling-)" data-toc-modified-id="Preprocessing-(Data-Scaling-)-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Preprocessing (Data Scaling )</a></span></li><li><span><a href="#Cross-Validatation" data-toc-modified-id="Cross-Validatation-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Cross Validatation</a></span></li><li><span><a href="#Hyperparameter-Tuning" data-toc-modified-id="Hyperparameter-Tuning-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Hyperparameter Tuning</a></span></li><li><span><a href="#Machine-Learning-Models" data-toc-modified-id="Machine-Learning-Models-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Machine Learning Models</a></span></li><li><span><a href="#Pipeline" data-toc-modified-id="Pipeline-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Pipeline</a></span></li></ul></div>

# Import Libraries

In [24]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 100)

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error 
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import median_absolute_error
from sklearn.metrics import r2_score
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.ensemble import RandomForestRegressor
import lightgbm as lgb

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.simplefilter("ignore")

# Load Data

In [3]:
train_df=pd.read_csv('train.csv')
test_df=pd.read_csv('test.csv')

In [4]:
train_df

,Year_Factor,State_Factor,building_class,facility_type,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui,id
0,1,State_1,Commercial,Grocery_store_or_food_market,61242.0,1942.0,11.0,2.4,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,NaN,248.682615,0
1,1,State_1,Commercial,Warehouse_Distribution_or_Shipping_center,274000.0,1955.0,45.0,1.8,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,NaN,1.0,12.0,26.500150,1
2,1,State_1,Commercial,Retail_Enclosed_mall,280025.0,1951.0,97.0,1.8,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,NaN,1.0,12.0,24.693619,2
3,1,State_1,Commercial,Education_Other_classroom,55325.0,1980.0,46.0,1.8,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,NaN,1.0,12.0,48.406926,3
4,1,State_1,Commercial,Warehouse_Nonrefrigerated,66000.0,1985.0,100.0,2.4,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,NaN,3.899395,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75752,6,State_11,Commercial,Office_Uncategorized,20410.0,1995.0,8.0,36.6,28,43.451613,56,34,47.672414,64,35,49.354839,71,40,56.266667,89,45,59.193548,88,47,63.566667,91,54,66.951613,87,52,68.612903,91,44,61.383333,79,39,55.403226,68,40,51.283333,71,24,38.532258,51,260,3772,45.03,1.4,1,55.147541,6,0,0,0,25,3,0,0,NaN,NaN,NaN,NaN,132.918411,75752
75753,6,State_11,Residential,5plus_Unit_Building,40489.0,1910.0,98.0,36.6,28,43.451613,56,34,47.672414,64,35,49.354839,71,40,56.266667,89,45,59.193548,88,47,63.566667,91,54,66.951613,87,52,68.612903,91,44,61.383333,79,39,55.403226,68,40,51.283333,71,24,38.532258,51,260,3772,45.03,1.4,1,55.147541,6,0,0,0,25,3,0,0,NaN,NaN,NaN,NaN,39.483672,75753
75754,6,State_11,Commercial,Commercial_Other,28072.0,1917.0,NaN,36.6,26,36.612903,48,30,41.637931,58,29,41.338710,62,34,50.183333,79,40,52.145161,79,41,56.233333,86,48,58.758065,81,48,61.612903,87,41,53.783333,73,37,47.661290,59,34,44.650000,62,15,30.338710,46,55,6218,106.32,36.6,438,47.911202,26,2,0,0,6,0,0,0,NaN,NaN,NaN,NaN,48.404398,75754
75755,6,State_11,Commercial,Commercial_Other,53575.0,2012.0,NaN,36.6,26,36.612903,48,30,41.637931,58,29,41.338710,62,34,50.183333,79,40,52.145161,79,41,56.233333,86,48,58.758065,81,48,61.612903,87,41,53.783333,73,37,47.661290,59,34,44.650000,62,15,30.338710,46,55,6218,106.32,36.6,438,47.911202,26,2,0,0,6,0,0,0,NaN,NaN,NaN,NaN,592.022750,75755
75756,6,State_11,Residential,2to4_Unit_Building,23888.0,1974.0,51.0,36.6,27,36.935484,51,29,42.172414,60,30,41.403226,66,36,51.533333,85,41,53.887097,80,41,58.433333,90,48,60.532258,83,49,64.338710,90,43,55.931034,75,40,48.532258,60,31,45.150000,69,18,30.919355,42,148,5853,107.69,28.8,377,49.127397,17,1,0,0,16,0,0,0,NaN,NaN,NaN,NaN,29.154684,75756

# Exploratory Data Analysis

In [5]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75757 entries, 0 to 75756
Data columns (total 64 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year_Factor                75757 non-null  int64
 1   State_Factor               75757 non-null  object
 2   building_class             75757 non-null  object
 3   facility_type              75757 non-null  object
 4   floor_area                 75757 non-null  float64
 5   year_built                 73920 non-null  float64
 6   energy_star_rating         49048 non-null  float64
 7   ELEVATION                  75757 non-null  float64
 8   january_min_temp           75757 non-null  int64
 9   january_avg_temp           75757 non-null  float64
 10  january_max_temp           75757 non-null  int64
 11  february_min_temp          75757 non-null  int64
 12  february_avg_temp          75757 non-null  float64
 13  february_max_temp          75757 non-null  int64
 14  march_min_temp             75757 non-null  int64
 15  march_avg_temp             75757 non-null  float64
 16  march_max_temp             75757 non-null  int64
 17  april_min_temp             75757 non-null  int64
 18  april_avg_temp             75757 non-null  float64
 19  april_max_temp             75757 non-null  int64
 20  may_min_temp               75757 non-null  int64
 21  may_avg_temp               75757 non-null  float64
 22  may_max_temp               75757 non-null  int64
 23  june_min_temp              75757 non-null  int64
 24  june_avg_temp              75757 non-null  float64
 25  june_max_temp              75757 non-null  int64
 26  july_min_temp              75757 non-null  int64
 27  july_avg_temp              75757 non-null  float64
 28  july_max_temp              75757 non-null  int64
 29  august_min_temp            75757 non-null  int64
 30  august_avg_temp            75757 non-null  float64
 31  august_max_temp            75757 non-null  int64
 32  september_min_temp         75757 non-null  int64
 33  september_avg_temp         75757 non-null  float64
 34  september_max_temp         75757 non-null  int64
 35  october_min_temp           75757 non-null  int64
 36  october_avg_temp           75757 non-null  float64
 37  october_max_temp           75757 non-null  int64
 38  november_min_temp          75757 non-null  int64
 39  november_avg_temp          75757 non-null  float64
 40  november_max_temp          75757 non-null  int64
 41  december_min_temp          75757 non-null  int64
 42  december_avg_temp          75757 non-null  float64
 43  december_max_temp          75757 non-null  int64
 44  cooling_degree_days        75757 non-null  int64
 45  heating_degree_days        75757 non-null  int64
 46  precipitation_inches       75757 non-null  float64
 47  snowfall_inches            75757 non-null  float64
 48  snowdepth_inches           75757 non-null  int64
 49  avg_temp                   75757 non-null  float64
 50  days_below_30F             75757 non-null  int64
 51  days_below_20F             75757 non-null  int64
 52  days_below_10F             75757 non-null  int64
 53  days_below_0F              75757 non-null  int64
 54  days_above_80F             75757 non-null  int64
 55  days_above_90F             75757 non-null  int64
 56  days_above_100F            75757 non-null  int64
 57  days_above_110F            75757 non-null  int64
 58  direction_max_wind_speed   34675 non-null  float64
 59  direction_peak_wind_speed  33946 non-null  float64
 60  max_wind_speed             34675 non-null  float64
 61  days_with_fog              29961 non-null  float64
 62  site_eui                   75757 non-null  float64
 63  id                         75757 non-null  int64
dtypes: float64(24), int64(37), object(3)
memory usage: 37.0+ MB

In [6]:
train_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Year_Factor,75757.0,4.367755,1.471441,1.000000,3.000000,5.000000,6.000000,6.000000e+00
floor_area,75757.0,165983.865858,246875.790940,943.000000,62379.000000,91367.000000,166000.000000,6.385382e+06
year_built,73920.0,1952.306764,37.053619,0.000000,1927.000000,1951.000000,1977.000000,2.015000e+03
energy_star_rating,49048.0,61.048605,28.663683,0.000000,40.000000,67.000000,85.000000,1.000000e+02
ELEVATION,75757.0,39.506323,60.656596,-6.400000,11.900000,25.000000,42.700000,1.924500e+03
january_min_temp,75757.0,11.432343,9.381027,-19.000000,6.000000,11.000000,13.000000,4.900000e+01
january_avg_temp,75757.0,34.310468,6.996108,10.806452,29.827586,34.451613,37.322581,6.475806e+01
january_max_temp,75757.0,59.054952,5.355458,42.000000,56.000000,59.000000,62.000000,9.100000e+01
february_min_temp,75757.0,11.720567,12.577272,-13.000000,2.000000,9.000000,20.000000,4.800000e+01
february_avg_temp,75757.0,35.526837,8.866697,13.250000,31.625000,34.107143,40.879310,6.510714e+01
february_max_temp,75757.0,58.486278,8.414611,38.000000,55.000000,61.000000,62.000000,8.900000e+01
march_min_temp,75757.0,21.606281,10.004303,-9.000000,13.000000,25.000000,27.000000,5.200000e+01
march_avg_temp,75757.0,44.469292,6.657142,25.854839,38.096774,44.516129,49.354839,6.975806e+01
march_max_temp,75757.0,70.897831,7.680982,53.000000,62.000000,71.000000,78.000000,9.500000e+01
april_min_temp,75757.0,32.037171,5.577279,15.000000,26.000000,32.000000,37.000000,5.200000e+01
april_avg_temp,75757.0,53.784863,2.500473,40.280000,52.333333,53.333333,54.766667,7.450000e+01
april_max_temp,75757.0,82.661932,4.101028,62.000000,80.000000,82.000000,87.000000,1.040000e+02
may_min_temp,75757.0,44.706179,4.200319,23.000000,42.000000,45.000000,49.000000,5.800000e+01
may_avg_temp,75757.0,63.742547,2.792919,46.950000,62.790323,62.887097,65.096774,8.211290e+01
may_max_temp,75757.0,88.987856,2.864669,64.000000,88.000000,89.000000,91.000000,1.120000e+02
june_min_temp,75757.0,51.131763,3.415926,30.000000,50.000000,52.000000,53.000000,6.800000e+01
june_avg_temp,75757.0,71.066384,2.861681,54.100000,70.983333,72.250000,72.450000,8.955000e+01
june_max_temp,75757.0,91.400280,3.604068,67.000000,89.000000,90.000000,94.000000,1.190000e+02
july_min_temp,75757.0,60.571604,4.177109,37.000000,57.000000,63.000000,63.000000,7.400000e+01
july_avg_temp,75757.0,76.596879,4.090275,54.822581,76.145161,78.677419,78.790323,9.443548e+01
july_max_temp,75757.0,95.543950,4.157118,65.000000,95.000000,96.000000,98.000000,1.170000e+02
august_min_temp,75757.0,58.515068,4.441992,31.000000,57.000000,61.000000,61.000000,7.700000e+01
august_avg_temp,75757.0,75.348749,3.818895,56.693548,74.516129,75.725806,78.967742,9.490323e+01
august_max_temp,75757.0,92.572581,4.139685,66.000000,90.000000,91.000000,95.000000,1.160000e+02
september_min_temp,75757.0,50.791689,4.290884,26.000000,47.000000,52.000000,54.000000,6.500000e+01
september_avg_temp,75757.0,69.597545,3.603773,53.600000,68.200000,69.733333,71.800000,9.011667e+01
september_max_temp,75757.0,92.171139,5.011708,64.000000,91.000000,92.000000,96.000000,1.110000e+02
october_min_temp,75757.0,38.210911,5.093899,18.000000,35.000000,38.000000,40.000000,6.100000e+01
october_avg_temp,75757.0,58.727038,2.641300,44.693548,58.048387,58.758065,59.629032,8.074194e+01
october_max_temp,75757.0,81.135671,5.579513,59.000000,78.000000,80.000000,85.000000,1.080000e+02
november_min_temp,75757.0,28.630397,7.153244,4.000000,23.000000,31.000000,34.000000,5.200000e+01
november_avg_temp,75757.0,48.123133,4.094207,30.766667,45.250000,47.116667,51.339286,6.741667e+01
november_max_temp,75757.0,71.202397,4.373374,53.000000,69.000000,72.000000,74.000000,9.600000e+01
december_min_temp,75757.0,22.736777,9.014047,-16.000000,17.000000,24.000000,28.000000,4.400000e+01
december_avg_temp,75757.0,41.625569,5.869386,23.790323,38.532258,40.516129,43.435484,6.179032e+01
december_max_temp,75757.0,64.496852,6.054104,42.000000,60.000000,65.000000,71.000000,8.600000e+01
cooling_degree_days,75757.0,1202.250446,391.561780,0.000000,1128.000000,1277.000000,1489.000000,4.948000e+03
heating_degree_days,75757.0,4324.957390,824.366727,398.000000,3978.000000,4337.000000,4670.000000,7.929000e+03
precipitation_inches,75757.0,42.430651,10.592205,0.000000,39.350000,42.170000,46.320000,1.076900e+02
snowfall_inches,75757.0,29.136379,17.810894,0.000000,9.600000,31.600000,49.100000,1.273000e+02
snowdepth_inches,75757.0,164.862455,175.275869,0.000000,10.000000,101.000000,377.000000,1.292000e+03
avg_temp,75757.0,56.176705,2.241940,44.512329,55.147541,56.835616,57.215847,7.724521e+01
days_below_30F,75757.0,48.756511,27.587124,0.000000,22.000000,50.000000,66.000000,1.700000e+02
days_below_20F,75757.0,17.447932,14.469435,0.000000,5.000000,11.000000,26.000000,9.300000e+01
days_below_10F,75757.0,4.886532,7.071221,0.000000,0.000000,2.000000,7.000000,5.900000e+01
days_below_0F,75757.0,0.876764,2.894244,0.000000,0.000000,0.000000,0.000000,3.100000e+01
days_above_80F,75757.0,82.709809,25.282913,0.000000,72.000000,84.000000,97.000000,2.600000e+02
days_above_90F,75757.0,14.058701,10.943996,0.000000,6.000000,12.000000,17.000000,1.850000e+02
days_above_100F,75757.0,0.279539,2.252323,0.000000,0.000000,0.000000,0.000000,1.190000e+02
days_above_110F,75757.0,0.002442,0.142140,0.000000,0.000000,0.000000,0.000000,1.600000e+01
direction_max_wind_speed,34675.0,66.552675,131.147834,1.000000,1.000000,1.000000,1.000000,3.600000e+02
direction_peak_wind_speed,33946.0,62.779974,130.308106,1.000000,1.000000,1.000000,1.000000,3.600000e+02
max_wind_speed,34675.0,4.190601,6.458789,1.000000,1.000000,1.000000,1.000000,2.330000e+01
days_with_fog,29961.0,109.142051,50.699751,12.000000,88.000000,104.000000,131.000000,3.110000e+02
site_eui,75757.0,82.584693,58.255403,1.001169,54.528601,75.293716,97.277534,9.978661e+02
id,75757.0,37878.000000,21869.306509,0.000000,18939.000000,37878.000000,56817.000000,7.575600e+04

In [7]:
train_df.describe(include=['O']).T

                count unique                        top   freq
State_Factor    75757      7                    State_6  50840
building_class  75757      2                Residential  43558
facility_type   75757     60  Multifamily_Uncategorized  39455

In [8]:
train_df['State_Factor'].value_counts()

State_6     50840
State_11     6412
State_1      5618
State_2      4871
State_4      4300
State_8      3701
State_10       15
Name: State_Factor, dtype: int64

In [9]:
train_df['building_class'].value_counts()

Residential    43558
Commercial     32199
Name: building_class, dtype: int64

In [10]:
train_df['facility_type'].value_counts()

Multifamily_Uncategorized                    39455
Office_Uncategorized                         12512
Education_Other_classroom                     3860
Lodging_Hotel                                 2098
2to4_Unit_Building                            1893
Commercial_Other                              1744
5plus_Unit_Building                           1273
Warehouse_Nonrefrigerated                     1255
Retail_Uncategorized                          1130
Education_College_or_university               1056
Nursing_Home                                   772
Education_Uncategorized                        709
Mixed_Use_Commercial_and_Residential           672
Lodging_Dormitory_or_fraternity_sorority       669
Warehouse_Distribution_or_Shipping_center      604
Warehouse_Selfstorage                          577
Grocery_store_or_food_market                   448
Office_Medical_non_diagnostic                  447
Health_Care_Inpatient                          409
Religious_worship                              399
Industrial                                     384
Warehouse_Uncategorized                        330
Mixed_Use_Predominantly_Commercial             256
Parking_Garage                                 251
Office_Bank_or_other_financial                 173
Public_Assembly_Library                        160
Public_Safety_Fire_or_police_station           157
Public_Assembly_Other                          142
Service_Vehicle_service_repair_shop            138
Retail_Enclosed_mall                           120
Retail_Strip_shopping_mall                     113
Warehouse_Refrigerated                         113
Public_Assembly_Entertainment_culture          110
Education_Preschool_or_daycare                 108
Laboratory                                     107
Commercial_Unknown                              95
Public_Assembly_Social_meeting                  88
Lodging_Other                                   75
Retail_Vehicle_dealership_showroom              74
Public_Assembly_Recreation                      72
Food_Sales                                      70
Public_Assembly_Drama_theater                   70
Service_Uncategorized                           68
Food_Service_Restaurant_or_cafeteria            64
Health_Care_Outpatient_Clinic                   56
Health_Care_Uncategorized                       51
Public_Safety_Uncategorized                     43
Public_Assembly_Movie_Theater                   39
Public_Safety_Courthouse                        38
Public_Safety_Penitentiary                      37
Health_Care_Outpatient_Uncategorized            36
Data_Center                                     27
Public_Assembly_Uncategorized                   25
Office_Mixed_use                                18
Food_Service_Uncategorized                      18
Food_Service_Other                              17
Mixed_Use_Predominantly_Residential              9
Public_Assembly_Stadium                          9
Service_Drycleaning_or_Laundry                   9
Lodging_Uncategorized                            5
Name: facility_type, dtype: int64

*Analyze by pivoting features*

In [11]:
train_df[['State_Factor', 'site_eui']].groupby(['State_Factor'], as_index=False).mean().sort_values(by='site_eui', ascending=False)

  State_Factor   site_eui
4      State_4  95.199291
5      State_6  87.481012
6      State_8  87.416018
3      State_2  77.873978
1     State_10  68.597082
0      State_1  62.196194
2     State_11  53.989234

In [12]:
train_df[['building_class', 'site_eui']].groupby(['building_class'], as_index=False).mean().sort_values(by='site_eui', ascending=False)

  building_class   site_eui
0     Commercial  85.755239
1    Residential  80.240957

In [13]:
train_df[['facility_type', 'site_eui']].groupby(['facility_type'], as_index=False).mean().sort_values(by='site_eui', ascending=False)

                                facility_type    site_eui
4                                 Data_Center  339.734876
19                                 Laboratory  329.448470
14                      Health_Care_Inpatient  248.340597
13               Grocery_store_or_food_market  241.135162
11       Food_Service_Restaurant_or_cafeteria  195.593925
16       Health_Care_Outpatient_Uncategorized  189.892345
17                  Health_Care_Uncategorized  183.945201
45                 Public_Safety_Penitentiary  170.904892
41                    Public_Assembly_Stadium  157.041663
54        Service_Vehicle_service_repair_shop  137.595749
9                                  Food_Sales  136.793222
28                               Nursing_Home  131.313887
44       Public_Safety_Fire_or_police_station  131.122766
12                 Food_Service_Uncategorized  128.801496
38                      Public_Assembly_Other  126.704295
18                                 Industrial  125.345295
22                              Lodging_Other  120.958325
35      Public_Assembly_Entertainment_culture  118.900412
30              Office_Medical_non_diagnostic  116.762294
39                 Public_Assembly_Recreation  115.177708
53                      Service_Uncategorized  113.565430
3                          Commercial_Unknown  113.151628
49                 Retail_Strip_shopping_mall  110.418481
5             Education_College_or_university  108.629116
36                    Public_Assembly_Library  105.849109
21                              Lodging_Hotel  104.934997
15              Health_Care_Outpatient_Clinic  103.613131
43                   Public_Safety_Courthouse  103.182163
37              Public_Assembly_Movie_Theater  103.095275
48                       Retail_Enclosed_mall  100.965937
57                     Warehouse_Refrigerated   96.525301
2                            Commercial_Other   92.642037
29             Office_Bank_or_other_financial   89.895736
24       Mixed_Use_Commercial_and_Residential   89.529798
27                  Multifamily_Uncategorized   83.878522
46                Public_Safety_Uncategorized   83.709161
31                           Office_Mixed_use   82.110316
26        Mixed_Use_Predominantly_Residential   81.797872
20   Lodging_Dormitory_or_fraternity_sorority   81.595825
34              Public_Assembly_Drama_theater   80.916723
50                       Retail_Uncategorized   80.902854
40             Public_Assembly_Social_meeting   78.921954
32                       Office_Uncategorized   77.074389
6                   Education_Other_classroom   69.441531
25         Mixed_Use_Predominantly_Commercial   69.133400
33                             Parking_Garage   67.351241
23                      Lodging_Uncategorized   66.595438
42              Public_Assembly_Uncategorized   62.872612
7              Education_Preschool_or_daycare   60.974215
51         Retail_Vehicle_dealership_showroom   46.640952
8                     Education_Uncategorized   46.172799
47                          Religious_worship   44.560675
52             Service_Drycleaning_or_Laundry   42.112542
55  Warehouse_Distribution_or_Shipping_center   39.559542
56                  Warehouse_Nonrefrigerated   38.209399
1                         5plus_Unit_Building   36.737785
59                    Warehouse_Uncategorized   35.936435
0                          2to4_Unit_Building   31.876915
10                         Food_Service_Other   29.236616
58                      Warehouse_Selfstorage   21.589284

In [14]:
train_df[['Year_Factor', 'site_eui']].groupby(['Year_Factor'], as_index=False).mean().sort_values(by='site_eui', ascending=False)

   Year_Factor   site_eui
0            1  93.821420
3            4  86.991404
2            3  85.544105
1            2  82.709375
4            5  80.358158
5            6  79.315110

*Correlation between target and feautures*

In [15]:
#train_df.c(convert_numeric = True
correlation=train_df.corr()[['site_eui']].sort_values(by='site_eui',ascending=False)
correlation

                           site_eui
site_eui                   1.000000
snowfall_inches            0.157284
heating_degree_days        0.147861
days_below_30F             0.139811
july_avg_temp              0.133856
cooling_degree_days        0.125004
june_avg_temp              0.122019
days_below_20F             0.119492
august_avg_temp            0.113786
precipitation_inches       0.113558
snowdepth_inches           0.113371
september_avg_temp         0.108853
july_min_temp              0.108092
september_max_temp         0.098326
august_min_temp            0.091616
days_above_80F             0.086347
days_below_10F             0.084296
floor_area                 0.073967
may_avg_temp               0.072271
days_below_0F              0.060981
september_min_temp         0.060203
december_max_temp          0.054068
july_max_temp              0.047884
june_min_temp              0.042291
may_max_temp               0.031679
august_max_temp            0.028359
october_max_temp           0.021272
year_built                 0.017162
direction_peak_wind_speed  0.013589
november_max_temp          0.012002
ELEVATION                  0.011798
max_wind_speed             0.010639
direction_max_wind_speed   0.010217
may_min_temp              -0.002043
days_above_90F            -0.007980
days_above_110F           -0.014190
id                        -0.026500
june_max_temp             -0.029233
october_avg_temp          -0.040162
Year_Factor               -0.045179
days_above_100F           -0.050029
december_avg_temp         -0.050328
days_with_fog             -0.055388
december_min_temp         -0.058888
march_max_temp            -0.064302
november_avg_temp         -0.069882
april_max_temp            -0.078969
avg_temp                  -0.089201
october_min_temp          -0.095334
january_max_temp          -0.097070
november_min_temp         -0.100349
february_max_temp         -0.106693
april_min_temp            -0.111528
april_avg_temp            -0.113008
march_min_temp            -0.134110
march_avg_temp            -0.135303
february_min_temp         -0.147348
february_avg_temp         -0.154071
january_avg_temp          -0.167982
january_min_temp          -0.179190
energy_star_rating        -0.511012

# Cleaning Data (Handling missing values)

In [16]:
# check number of missing values in data

round(train_df.isna().sum()* 100 / len(train_df),2)

Year_Factor                   0.00
State_Factor                  0.00
building_class                0.00
facility_type                 0.00
floor_area                    0.00
year_built                    2.42
energy_star_rating           35.26
ELEVATION                     0.00
january_min_temp              0.00
january_avg_temp              0.00
january_max_temp              0.00
february_min_temp             0.00
february_avg_temp             0.00
february_max_temp             0.00
march_min_temp                0.00
march_avg_temp                0.00
march_max_temp                0.00
april_min_temp                0.00
april_avg_temp                0.00
april_max_temp                0.00
may_min_temp                  0.00
may_avg_temp                  0.00
may_max_temp                  0.00
june_min_temp                 0.00
june_avg_temp                 0.00
june_max_temp                 0.00
july_min_temp                 0.00
july_avg_temp                 0.00
july_max_temp                 0.00
august_min_temp               0.00
august_avg_temp               0.00
august_max_temp               0.00
september_min_temp            0.00
september_avg_temp            0.00
september_max_temp            0.00
october_min_temp              0.00
october_avg_temp              0.00
october_max_temp              0.00
november_min_temp             0.00
november_avg_temp             0.00
november_max_temp             0.00
december_min_temp             0.00
december_avg_temp             0.00
december_max_temp             0.00
cooling_degree_days           0.00
heating_degree_days           0.00
precipitation_inches          0.00
snowfall_inches               0.00
snowdepth_inches              0.00
avg_temp                      0.00
days_below_30F                0.00
days_below_20F                0.00
days_below_10F                0.00
days_below_0F                 0.00
days_above_80F                0.00
days_above_90F                0.00
days_above_100F               0.00
days_above_110F               0.00
direction_max_wind_speed     54.23
direction_peak_wind_speed    55.19
max_wind_speed               54.23
days_with_fog                60.45
site_eui                      0.00
id                            0.00
dtype: float64

In [17]:
# #(1) using KNNImputer
# imputer = KNNImputer()
# for col in ['year_built','energy_star_rating','direction_max_wind_speed','direction_peak_wind_speed','max_wind_speed','days_with_fog']:
#     train_df[col]=imputer.fit_transform(train_df[[col]])

In [18]:
#(2) using SimpleImputer
imputer = SimpleImputer(strategy='median')
train_df['year_built']= imputer.fit_transform(train_df[['year_built']])
train_df['energy_star_rating']= imputer.fit_transform(train_df[['energy_star_rating']])
train_df['direction_max_wind_speed']= imputer.fit_transform(train_df[['direction_max_wind_speed']])
train_df['direction_peak_wind_speed']= imputer.fit_transform(train_df[['direction_peak_wind_speed']])
train_df['max_wind_speed']= imputer.fit_transform(train_df[['max_wind_speed']])
train_df['days_with_fog']= imputer.fit_transform(train_df[['days_with_fog']])

In [19]:
train_df.drop(['id'],axis=1,inplace=True)

In [20]:
round(train_df.isna().sum()* 100 / len(train_df),2)

Year_Factor                  0.0
State_Factor                 0.0
building_class               0.0
facility_type                0.0
floor_area                   0.0
year_built                   0.0
energy_star_rating           0.0
ELEVATION                    0.0
january_min_temp             0.0
january_avg_temp             0.0
january_max_temp             0.0
february_min_temp            0.0
february_avg_temp            0.0
february_max_temp            0.0
march_min_temp               0.0
march_avg_temp               0.0
march_max_temp               0.0
april_min_temp               0.0
april_avg_temp               0.0
april_max_temp               0.0
may_min_temp                 0.0
may_avg_temp                 0.0
may_max_temp                 0.0
june_min_temp                0.0
june_avg_temp                0.0
june_max_temp                0.0
july_min_temp                0.0
july_avg_temp                0.0
july_max_temp                0.0
august_min_temp              0.0
august_avg_temp              0.0
august_max_temp              0.0
september_min_temp           0.0
september_avg_temp           0.0
september_max_temp           0.0
october_min_temp             0.0
october_avg_temp             0.0
october_max_temp             0.0
november_min_temp            0.0
november_avg_temp            0.0
november_max_temp            0.0
december_min_temp            0.0
december_avg_temp            0.0
december_max_temp            0.0
cooling_degree_days          0.0
heating_degree_days          0.0
precipitation_inches         0.0
snowfall_inches              0.0
snowdepth_inches             0.0
avg_temp                     0.0
days_below_30F               0.0
days_below_20F               0.0
days_below_10F               0.0
days_below_0F                0.0
days_above_80F               0.0
days_above_90F               0.0
days_above_100F              0.0
days_above_110F              0.0
direction_max_wind_speed     0.0
direction_peak_wind_speed    0.0
max_wind_speed               0.0
days_with_fog                0.0
site_eui                     0.0
dtype: float64

# Cleaning Data (Mistake Handling)

In [21]:
#  year_built have mistake value "0"
train_df.loc[train_df['year_built']==0,'year_built']=train_df['year_built'].median()

#  'ELEVATION' have mistake minuse value "-6.4000e+00"

# change   minus values using abs(x)
train_df['ELEVATION']=train_df['ELEVATION'].apply(lambda x:abs(x))

# Cleaning Data (Outliers Handling)

In [22]:
train_df.describe()

,Year_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui
count,75757.000000,7.575700e+04,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000,75757.000000
mean,4.367755,1.659839e+05,1952.429597,63.146838,39.506661,11.432343,34.310468,59.054952,11.720567,35.526837,58.486278,21.606281,44.469292,70.897831,32.037171,53.784863,82.661932,44.706179,63.742547,88.987856,51.131763,71.066384,91.400280,60.571604,76.596879,95.543950,58.515068,75.348749,92.572581,50.791689,69.597545,92.171139,38.210911,58.727038,81.135671,28.630397,48.123133,71.202397,22.736777,41.625569,64.496852,1202.250446,4324.957390,42.430651,29.136379,164.862455,56.176705,48.756511,17.447932,4.886532,0.876764,82.709809,14.058701,0.279539,0.002442,31.004343,28.683026,2.460381,106.033621,82.584693
std,1.471441,2.468758e+05,32.215321,23.238351,60.656376,9.381027,6.996108,5.355458,12.577272,8.866697,8.414611,10.004303,6.657142,7.680982,5.577279,2.500473,4.101028,4.200319,2.792919,2.864669,3.415926,2.861681,3.604068,4.177109,4.090275,4.157118,4.441992,3.818895,4.139685,4.290884,3.603773,5.011708,5.093899,2.641300,5.579513,7.153244,4.094207,4.373374,9.014047,5.869386,6.054104,391.561780,824.366727,10.592205,17.810894,175.275869,2.241940,27.587124,14.469435,7.071221,2.894244,25.282913,10.943996,2.252323,0.142140,94.546574,92.479537,4.649782,31.982643,58.255403
min,1.000000,9.430000e+02,1600.000000,0.000000,1.800000,-19.000000,10.806452,42.000000,-13.000000,13.250000,38.000000,-9.000000,25.854839,53.000000,15.000000,40.280000,62.000000,23.000000,46.950000,64.000000,30.000000,54.100000,67.000000,37.000000,54.822581,65.000000,31.000000,56.693548,66.000000,26.000000,53.600000,64.000000,18.000000,44.693548,59.000000,4.000000,30.766667,53.000000,-16.000000,23.790323,42.000000,0.000000,398.000000,0.000000,0.000000,0.000000,44.512329,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,12.000000,1.001169
25%,3.000000,6.237900e+04,1927.000000,56.000000,11.900000,6.000000,29.827586,56.000000,2.000000,31.625000,55.000000,13.000000,38.096774,62.000000,26.000000,52.333333,80.000000,42.000000,62.790323,88.000000,50.000000,70.983333,89.000000,57.000000,76.145161,95.000000,57.000000,74.516129,90.000000,47.000000,68.200000,91.000000,35.000000,58.048387,78.000000,23.000000,45.250000,69.000000,17.000000,38.532258,60.000000,1128.000000,3978.000000,39.350000,9.600000,10.000000,55.147541,22.000000,5.000000,0.000000,0.000000,72.000000,6.000000,0.000000,0.000000,1.000000,1.000000,1.000000,104.000000,54.528601
50%,5.000000,9.136700e+04,1951.000000,67.000000,25.000000,11.000000,34.451613,59.000000,9.000000,34.107143,61.000000,25.000000,44.516129,71.000000,32.000000,53.333333,82.000000,45.000000,62.887097,89.000000,52.000000,72.250000,90.000000,63.000000,78.677419,96.000000,61.000000,75.725806,91.000000,52.000000,69.733333,92.000000,38.000000,58.758065,80.000000,31.000000,47.116667,72.000000,24.000000,40.516129,65.000000,1277.000000,4337.000000,42.170000,31.600000,101.000000,56.835616,50.000000,11.000000,2.000000,0.000000,84.000000,12.000000,0.000000,0.000000,1.000000,1.000000,1.000000,104.000000,75.293716
75%,6.000000,1.660000e+05,1976.000000,76.000000,42.700000,13.000000,37.322581,62.000000,20.000000,40.879310,62.000000,27.000000,49.354839,78.000000,37.000000,54.766667,87.000000,49.000000,65.096774,91.000000,53.000000,72.450000,94.000000,63.000000,78.790323,98.000000,61.000000,78.967742,95.000000,54.000000,71.800000,96.000000,40.000000,59.629032,85.000000,34.000000,51.339286,74.000000,28.000000,43.435484,71.000000,1489.000000,4670.000000,46.320000,49.100000,377.000000,57.215847,66.000000,26.000000,7.000000,0.000000,97.000000,17.000000,0.000000,0.000000,1.000000,1.000000,1.000000,104.000000,97.277534
max,6.000000,6.385382e+06,2015.000000,100.000000,1924.500000,49.000000,64.758065,91.000000,48.000000,65.107143,89.000000,52.000000,69.758065,95.000000,52.000000,74.500000,104.000000,58.000000,82.112903,112.000000,68.000000,89.550000,119.000000,74.000000,94.435484,117.000000,77.000000,94.903226,116.000000,65.000000,90.116667,111.000000,61.000000,80.741935,108.000000,52.000000,67.416667,96.000000,44.000000,61.790323,86.000000,4948.000000,7929.000000,107.690000,127.300000,1292.000000,77.245205,170.000000,93.000000,59.000000,31.000000,260.000000,185.000000,119.000000,16.000000,360.000000,360.000000,23.300000,311.000000,997.866120

In [25]:
from datasist.structdata import detect_outliers
idx=detect_outliers(train_df,0,['floor_area','energy_star_rating','ELEVATION','year_built'])

In [26]:
outliers=train_df.loc[idx]
clean =train_df.drop(idx,axis=0)
outliers

,Year_Factor,State_Factor,building_class,facility_type,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui
13,1,State_1,Commercial,Data_Center,616793.0,1955.0,13.0,2.4,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.65,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,104.0,608.839519
42,1,State_1,Commercial,Office_Uncategorized,384203.0,1905.0,100.0,59.1,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.65,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,104.0,68.262915
48,1,State_1,Residential,Mixed_Use_Predominantly_Commercial,325369.0,2002.0,83.0,59.1,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.65,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,104.0,82.285107
56,1,State_1,Commercial,Office_Uncategorized,1011213.0,1920.0,70.0,59.1,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.65,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,104.0,142.478168
70,1,State_1,Commercial,Retail_Enclosed_mall,328873.0,1915.0,73.0,120.1,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.65,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,104.0,27.890293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68337,6,State_8,Commercial,Public_Assembly_Entertainment_culture,23860.0,1732.0,67.0,3.0,8,29.827586,62,4,33.896552,62,24,45.967742,79,18,49.931034,81,37,59.161290,89,45,70.465517,90,57,77.083333,96,54,75.725806,95,40,68.20,96,24,55.258065,85,20,44.316667,71,12,35.129032,58,1114,5074,35.78,13.9,18,53.839335,97,29,6,0,101,21,0,0,1.0,1.0,1.0,116.0,35.077000
68347,6,State_8,Residential,Multifamily_Uncategorized,51390.0,1845.0,51.0,3.0,8,29.827586,62,4,33.896552,62,24,45.967742,79,18,49.931034,81,37,59.161290,89,45,70.465517,90,57,77.083333,96,54,75.725806,95,40,68.20,96,24,55.258065,85,20,44.316667,71,12,35.129032,58,1114,5074,35.78,13.9,18,53.839335,97,29,6,0,101,21,0,0,1.0,1.0,1.0,116.0,41.879750
68427,6,State_8,Residential,Multifamily_Uncategorized,79733.0,1815.0,43.0,3.0,8,29.827586,62,4,33.896552,62,24,45.967742,79,18,49.931034,81,37,59.161290,89,45,70.465517,90,57,77.083333,96,54,75.725806,95,40,68.20,96,24,55.258065,85,20,44.316667,71,12,35.129032,58,1114,5074,35.78,13.9,18,53.839335,97,29,6,0,101,21,0,0,1.0,1.0,1.0,116.0,78.587366
68796,6,State_8,Commercial,Warehouse_Nonrefrigerated,100000.0,1800.0,67.0,3.0,8,29.827586,62,4,33.896552,62,24,45.967742,79,18,49.931034,81,37,59.161290,89,45,70.465517,90,57,77.083333,96,54,75.725806,95,40,68.20,96,24,55.258065,85,20,44.316667,71,12,35.129032,58,1114,5074,35.78,13.9,18,53.839335,97,29,6,0,101,21,0,0,1.0,1.0,1.0,116.0,6.264004
69000,6,State_8,Commercial,Warehouse_Nonrefrigerated,68632.0,1850.0,86.0,18.3,8,29.827586,62,4,33.896552,62,24,45.967742,79,18,49.931034,81,37,59.161290,89,45,70.465517,90,57,77.083333,96,54,75.725806,95,40,68.20,96,24,55.258065,85,20,44.316667,71,12,35.129032,58,1114,5074,35.78,13.9,18,53.839335,97,29,6,0,101,21,0,0,1.0,1.0,1.0,104.0,5.838053

# Preprocessing (Data Encoding )

In [27]:
# using dummies
train_df=pd.get_dummies( data=train_df,columns=['State_Factor','building_class','facility_type'],drop_first=True)
train_df

,Year_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui,State_Factor_State_10,State_Factor_State_11,State_Factor_State_2,State_Factor_State_4,State_Factor_State_6,State_Factor_State_8,building_class_Residential,facility_type_5plus_Unit_Building,facility_type_Commercial_Other,facility_type_Commercial_Unknown,facility_type_Data_Center,facility_type_Education_College_or_university,facility_type_Education_Other_classroom,facility_type_Education_Preschool_or_daycare,facility_type_Education_Uncategorized,facility_type_Food_Sales,facility_type_Food_Service_Other,facility_type_Food_Service_Restaurant_or_cafeteria,facility_type_Food_Service_Uncategorized,facility_type_Grocery_store_or_food_market,facility_type_Health_Care_Inpatient,facility_type_Health_Care_Outpatient_Clinic,facility_type_Health_Care_Outpatient_Uncategorized,facility_type_Health_Care_Uncategorized,facility_type_Industrial,facility_type_Laboratory,facility_type_Lodging_Dormitory_or_fraternity_sorority,facility_type_Lodging_Hotel,facility_type_Lodging_Other,facility_type_Lodging_Uncategorized,facility_type_Mixed_Use_Commercial_and_Residential,facility_type_Mixed_Use_Predominantly_Commercial,facility_type_Mixed_Use_Predominantly_Residential,facility_type_Multifamily_Uncategorized,facility_type_Nursing_Home,facility_type_Office_Bank_or_other_financial,facility_type_Office_Medical_non_diagnostic,facility_type_Office_Mixed_use,facility_type_Office_Uncategorized,facility_type_Parking_Garage,facility_type_Public_Assembly_Drama_theater,facility_type_Public_Assembly_Entertainment_culture,facility_type_Public_Assembly_Library,facility_type_Public_Assembly_Movie_Theater,facility_type_Public_Assembly_Other,facility_type_Public_Assembly_Recreation,facility_type_Public_Assembly_Social_meeting,facility_type_Public_Assembly_Stadium,facility_type_Public_Assembly_Uncategorized,facility_type_Public_Safety_Courthouse,facility_type_Public_Safety_Fire_or_police_station,facility_type_Public_Safety_Penitentiary,facility_type_Public_Safety_Uncategorized,facility_type_Religious_worship,facility_type_Retail_Enclosed_mall,facility_type_Retail_Strip_shopping_mall,facility_type_Retail_Uncategorized,facility_type_Retail_Vehicle_dealership_showroom,facility_type_Service_Drycleaning_or_Laundry,facility_type_Service_Uncategorized,facility_type_Service_Vehicle_service_repair_shop,facility_type_Warehouse_Distribution_or_Shipping_center,facility_type_Warehouse_Nonrefrigerated,facility_type_Warehouse_Refrigerated,facility_type_Warehouse_Selfstorage,facility_type_Warehouse_Uncategorized
0,1,61242.0,1942.0,11.0,2.4,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,104.0,248.682615,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,274000.0,1955.0,45.0,1.8,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,12.0,26.500150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,1,280025.0,1951.0,97.0,1.8,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,12.0,24.693619,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,1,55325.0,1980.0,46.0,1.8,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,12.0,48.406926,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,66000.0,1985.0,100.0,2.4,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,104.0,3.899395,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75752,6,20410.0,1995.0,8.0,36.6,28,43.451613,56,34,47.672414,64,35,49.354839,71,40,56.266667,89,45,59.193548,88,47,63.566667,91,54,66.951613,87,52,68.612903,91,44,61.383333,79,39,55.403226,68,40,51.283333,71,24,38.532258,51,260,3772,45.03,1.4,1,55.147541,6,0,0,0,25,3,0,0,1.0,1.0,1.0,104.0,132.918411,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75753,6,40489.0,1910.0,98.0,36.6,28,43.451613,56,34,47.672414,64,35,49.354839,71,40,56.266667,89,45,59.193548,88,47,63.566667,91,54,66.951613,87,52,68.612903,91,44,61.383333,79,39,55.403226,68,40,51.283333,71,24,38.532258,51,260,3772,45.03,1.4,1,55.147541,6,0,0,0,25,3,0,0,1.0,1.0,1.0,104.0,39.483672,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75754,6,28072.0,1917.0,67.0,36.6,26,36.612903,48,30,41.637931,58,29,41.338710,62,34,50.183333,79,40,52.145161,79,41,56.233333,86,48,58.758065,81,48,61.612903,87,41,53.783333,73,37,47.661290,59,34,44.650000,62,15,30.338710,46,55,6218,106.32,36.6,438,47.911202,26,2,0,0,6,0,0,0,1.0,1.0,1.0,104.0,48.404398,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75755,6,53575.0,2012.0,67.0,36.6,26,36.612903,48,30,41.637931,58,29,41.338710,62,34,50.183333,79,40,52.145161,79,41,56.233333,86,48,58.758065,81,48,61.612903,87,41,53.783333,73,37,47.661290,59,34,44.650000,62,15,30.338710,46,55,6218,106.32,36.6,438,47.911202,26,2,0,0,6,0,0,0,1.0,1.0,1.0,104.0,592.022750,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75756,6,23888.0,1974.0,51.0,36.6,27,36.935484,51,29,42.172414,60,30,41.403226,66,36,51.533333,85,41,53.887097,80,41,58.433333,90,48,60.532258,83,49,64.338710,90,43,55.931034,75,40,48.532258,60,31,45.150000,69,18,30.919355,42,148,5853,107.69,28.8,377,49.127397,17,1,0,0,16,0,0,0,1.0,1.0,1.0,104.0,29.154684,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

# Preprocessing (Feature Selection )

In [28]:
X = train_df.drop(['site_eui'], axis=1)
Y = train_df['site_eui']

In [29]:
X

,Year_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,State_Factor_State_10,State_Factor_State_11,State_Factor_State_2,State_Factor_State_4,State_Factor_State_6,State_Factor_State_8,building_class_Residential,facility_type_5plus_Unit_Building,facility_type_Commercial_Other,facility_type_Commercial_Unknown,facility_type_Data_Center,facility_type_Education_College_or_university,facility_type_Education_Other_classroom,facility_type_Education_Preschool_or_daycare,facility_type_Education_Uncategorized,facility_type_Food_Sales,facility_type_Food_Service_Other,facility_type_Food_Service_Restaurant_or_cafeteria,facility_type_Food_Service_Uncategorized,facility_type_Grocery_store_or_food_market,facility_type_Health_Care_Inpatient,facility_type_Health_Care_Outpatient_Clinic,facility_type_Health_Care_Outpatient_Uncategorized,facility_type_Health_Care_Uncategorized,facility_type_Industrial,facility_type_Laboratory,facility_type_Lodging_Dormitory_or_fraternity_sorority,facility_type_Lodging_Hotel,facility_type_Lodging_Other,facility_type_Lodging_Uncategorized,facility_type_Mixed_Use_Commercial_and_Residential,facility_type_Mixed_Use_Predominantly_Commercial,facility_type_Mixed_Use_Predominantly_Residential,facility_type_Multifamily_Uncategorized,facility_type_Nursing_Home,facility_type_Office_Bank_or_other_financial,facility_type_Office_Medical_non_diagnostic,facility_type_Office_Mixed_use,facility_type_Office_Uncategorized,facility_type_Parking_Garage,facility_type_Public_Assembly_Drama_theater,facility_type_Public_Assembly_Entertainment_culture,facility_type_Public_Assembly_Library,facility_type_Public_Assembly_Movie_Theater,facility_type_Public_Assembly_Other,facility_type_Public_Assembly_Recreation,facility_type_Public_Assembly_Social_meeting,facility_type_Public_Assembly_Stadium,facility_type_Public_Assembly_Uncategorized,facility_type_Public_Safety_Courthouse,facility_type_Public_Safety_Fire_or_police_station,facility_type_Public_Safety_Penitentiary,facility_type_Public_Safety_Uncategorized,facility_type_Religious_worship,facility_type_Retail_Enclosed_mall,facility_type_Retail_Strip_shopping_mall,facility_type_Retail_Uncategorized,facility_type_Retail_Vehicle_dealership_showroom,facility_type_Service_Drycleaning_or_Laundry,facility_type_Service_Uncategorized,facility_type_Service_Vehicle_service_repair_shop,facility_type_Warehouse_Distribution_or_Shipping_center,facility_type_Warehouse_Nonrefrigerated,facility_type_Warehouse_Refrigerated,facility_type_Warehouse_Selfstorage,facility_type_Warehouse_Uncategorized
0,1,61242.0,1942.0,11.0,2.4,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,104.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,274000.0,1955.0,45.0,1.8,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,12.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,1,280025.0,1951.0,97.0,1.8,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,12.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,1,55325.0,1980.0,46.0,1.8,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,12.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,66000.0,1985.0,100.0,2.4,36,50.500000,68,35,50.589286,73,40,53.693548,80,41,55.500000,78,46,56.854839,84,50,60.500000,90,52,62.725806,84,52,62.161290,85,52,64.650000,90,47,63.016129,83,43,53.800000,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.0,1.0,104.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75752,6,20410.0,1995.0,8.0,36.6,28,43.451613,56,34,47.672414,64,35,49.354839,71,40,56.266667,89,45,59.193548,88,47,63.566667,91,54,66.951613,87,52,68.612903,91,44,61.383333,79,39,55.403226,68,40,51.283333,71,24,38.532258,51,260,3772,45.03,1.4,1,55.147541,6,0,0,0,25,3,0,0,1.0,1.0,1.0,104.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75753,6,40489.0,1910.0,98.0,36.6,28,43.451613,56,34,47.672414,64,35,49.354839,71,40,56.266667,89,45,59.193548,88,47,63.566667,91,54,66.951613,87,52,68.612903,91,44,61.383333,79,39,55.403226,68,40,51.283333,71,24,38.532258,51,260,3772,45.03,1.4,1,55.147541,6,0,0,0,25,3,0,0,1.0,1.0,1.0,104.0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75754,6,28072.0,1917.0,67.0,36.6,26,36.612903,48,30,41.637931,58,29,41.338710,62,34,50.183333,79,40,52.145161,79,41,56.233333,86,48,58.758065,81,48,61.612903,87,41,53.783333,73,37,47.661290,59,34,44.650000,62,15,30.338710,46,55,6218,106.32,36.6,438,47.911202,26,2,0,0,6,0,0,0,1.0,1.0,1.0,104.0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75755,6,53575.0,2012.0,67.0,36.6,26,36.612903,48,30,41.637931,58,29,41.338710,62,34,50.183333,79,40,52.145161,79,41,56.233333,86,48,58.758065,81,48,61.612903,87,41,53.783333,73,37,47.661290,59,34,44.650000,62,15,30.338710,46,55,6218,106.32,36.6,438,47.911202,26,2,0,0,6,0,0,0,1.0,1.0,1.0,104.0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75756,6,23888.0,1974.0,51.0,36.6,27,36.935484,51,29,42.172414,60,30,41.403226,66,36,51.533333,85,41,53.887097,80,41,58.433333,90,48,60.532258,83,49,64.338710,90,43,55.931034,75,40,48.532258,60,31,45.150000,69,18,30.919355,42,148,5853,107.69,28.8,377,49.127397,17,1,0,0,16,0,0,0,1.0,1.0,1.0,104.0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [30]:
from sklearn.feature_selection import f_regression, mutual_info_regression
from sklearn.feature_selection import SelectKBest, SelectPercentile
from sklearn.feature_selection import SelectFromModel

In [31]:
all_features = X.columns
all_features

Index(['Year_Factor', 'floor_area', 'year_built', 'energy_star_rating', 'ELEVATION',
       'january_min_temp', 'january_avg_temp', 'january_max_temp', 'february_min_temp',
       'february_avg_temp',
       ...
       'facility_type_Retail_Uncategorized', 'facility_type_Retail_Vehicle_dealership_showroom',
       'facility_type_Service_Drycleaning_or_Laundry', 'facility_type_Service_Uncategorized',
       'facility_type_Service_Vehicle_service_repair_shop',
       'facility_type_Warehouse_Distribution_or_Shipping_center',
       'facility_type_Warehouse_Nonrefrigerated', 'facility_type_Warehouse_Refrigerated',
       'facility_type_Warehouse_Selfstorage', 'facility_type_Warehouse_Uncategorized'],
      dtype='object', length=125)

In [32]:
#model = XGBRegressor()
#model=RandomForestRegressor(n_estimators=100,max_depth=2, random_state=33)
model=lgb.LGBMRegressor(num_leaves=50,learning_rate=0.05,n_estimators=20)

In [33]:
#selector = SelectKBest(k=60, score_func=f_regression)
#selector = SelectKBest(k=40, score_func=mutual_info_regression)
#selector = SelectPercentile(percentile=50, score_func=mutual_info_regression)
selector = SelectFromModel(estimator=model)

In [34]:
selector.fit(X, Y)

SelectFromModel(estimator=LGBMRegressor(learning_rate=0.05, n_estimators=20,
                                        num_leaves=50))

In [35]:
selected_features_idx = selector.get_support(indices=True)
selected_features_idx

array([  1,   2,   3,   5,   6,  20,  30,  45,  63,  65,  67,  70,  71,
        76,  78,  79,  81,  82,  83,  84,  86,  89,  92,  93,  95,  97,
        98, 120, 121, 123], dtype=int64)

In [36]:
selected_features = all_features[selected_features_idx]
selected_features

Index(['floor_area', 'year_built', 'energy_star_rating', 'january_min_temp', 'january_avg_temp',
       'june_min_temp', 'september_avg_temp', 'snowdepth_inches', 'State_Factor_State_6',
       'building_class_Residential', 'facility_type_Commercial_Other',
       'facility_type_Education_College_or_university', 'facility_type_Education_Other_classroom',
       'facility_type_Food_Service_Restaurant_or_cafeteria',
       'facility_type_Grocery_store_or_food_market', 'facility_type_Health_Care_Inpatient',
       'facility_type_Health_Care_Outpatient_Uncategorized',
       'facility_type_Health_Care_Uncategorized', 'facility_type_Industrial',
       'facility_type_Laboratory', 'facility_type_Lodging_Hotel',
       'facility_type_Mixed_Use_Commercial_and_Residential',
       'facility_type_Multifamily_Uncategorized', 'facility_type_Nursing_Home',
       'facility_type_Office_Medical_non_diagnostic', 'facility_type_Office_Uncategorized',
       'facility_type_Parking_Garage', 'facility_type_Warehouse_Distribution_or_Shipping_center',
       'facility_type_Warehouse_Nonrefrigerated', 'facility_type_Warehouse_Selfstorage'],
      dtype='object')

In [37]:
X[selected_features]

,floor_area,year_built,energy_star_rating,january_min_temp,january_avg_temp,june_min_temp,september_avg_temp,snowdepth_inches,State_Factor_State_6,building_class_Residential,facility_type_Commercial_Other,facility_type_Education_College_or_university,facility_type_Education_Other_classroom,facility_type_Food_Service_Restaurant_or_cafeteria,facility_type_Grocery_store_or_food_market,facility_type_Health_Care_Inpatient,facility_type_Health_Care_Outpatient_Uncategorized,facility_type_Health_Care_Uncategorized,facility_type_Industrial,facility_type_Laboratory,facility_type_Lodging_Hotel,facility_type_Mixed_Use_Commercial_and_Residential,facility_type_Multifamily_Uncategorized,facility_type_Nursing_Home,facility_type_Office_Medical_non_diagnostic,facility_type_Office_Uncategorized,facility_type_Parking_Garage,facility_type_Warehouse_Distribution_or_Shipping_center,facility_type_Warehouse_Nonrefrigerated,facility_type_Warehouse_Selfstorage
0,61242.0,1942.0,11.0,36,50.500000,50,64.650000,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,274000.0,1955.0,45.0,36,50.500000,50,64.650000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,280025.0,1951.0,97.0,36,50.500000,50,64.650000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,55325.0,1980.0,46.0,36,50.500000,50,64.650000,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,66000.0,1985.0,100.0,36,50.500000,50,64.650000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75752,20410.0,1995.0,8.0,28,43.451613,47,61.383333,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
75753,40489.0,1910.0,98.0,28,43.451613,47,61.383333,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75754,28072.0,1917.0,67.0,26,36.612903,41,53.783333,438,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75755,53575.0,2012.0,67.0,26,36.612903,41,53.783333,438,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75756,23888.0,1974.0,51.0,27,36.935484,41,55.931034,377,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

# Preprocessing ( Data Splitting)

In [38]:
# Splitting the data

X = X[selected_features]

Y = train_df['site_eui']

In [39]:
# X = train_df.drop(['site_eui'], axis=1)
# Y = train_df['site_eui']

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(60605, 30)
(15152, 30)
(60605,)
(15152,)

#  Preprocessing (Data Scaling )

In [41]:
cols=X_train.columns

In [42]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test =  scaler.transform(X_test)

In [43]:
X_train

array([[-0.32477046,  0.88797094, -0.56341284, ..., -0.08991088,
        -0.13024897, -0.08726212],
       [-0.38371062, -1.00617711,  0.16695394, ..., -0.08991088,
        -0.13024897, -0.08726212],
       [ 0.1877969 ,  0.08062915,  0.33880495, ..., -0.08991088,
        -0.13024897, -0.08726212],
       ...,
       [-0.34696205, -0.81986747,  0.16695394, ..., -0.08991088,
        -0.13024897, -0.08726212],
       [-0.34885034, -0.91302229,  0.16695394, ..., -0.08991088,
        -0.13024897, -0.08726212],
       [-0.48896294,  1.63320951,  1.45583649, ..., -0.08991088,
        -0.13024897, -0.08726212]])

# Cross Validatation

In [44]:
#model = LinearRegression(fit_intercept=True, normalize=True,copy_X=True,n_jobs=-1)
#model = SVR(C = 1.0 ,epsilon=0.1,kernel = 'rbf') # it also can be : linear, poly, rbf, sigmoid, precomputed
#model = DecisionTreeRegressorModel = DecisionTreeRegressor( max_depth=3,random_state=33)
#model = XGBRegressor()

In [45]:
from sklearn.model_selection import cross_validate

In [46]:
#RMSE=cross_validate(model,X, Y, cv = 5,return_train_score=True,scoring = 'neg_root_mean_squared_error')
#RMSE

# Hyperparameter Tuning

In [47]:
from sklearn.model_selection import GridSearchCV

In [48]:
#=======================================================================================
# Hyperparameter tuning SelectKBest using random grid search
#=======================================================================================
# SelectedModel = SelectKBest()
# SelectedParameters = {
#     'k': [10, 15, 20,25,30,35,40,45,50,55,60,64],
#     'score_func': [f_regression, 40]
# }

# GridSearchModel =  GridSearchCV(SelectedModel,SelectedParameters,scoring='r2', cv = 5,return_train_score=True)
# GridSearchModel.fit(X_train,y_train)

# sorted(GridSearchModel.cv_results_.keys())
# GridSearchResults = pd.DataFrame(GridSearchModel.cv_results_)[['mean_test_score', 'std_test_score', 'params' , 'rank_test_score' , 'mean_fit_time']]
# # Showing Results
# print('All Results are :\n', GridSearchResults )
# print('Best Score is :', GridSearchModel.best_score_)
# print('Best Parameters are :', GridSearchModel.best_params_)
# print('Best Estimator is :', GridSearchModel.best_estimator_)

In [49]:
# #=======================================================================================
# # Hyperparameter tuning LightGBM using random grid search
# #=======================================================================================
# #Set the minimum error arbitrarily large
# min = 99999999999999999999999 
# count = 0 #Used for keeping track of the iteration number
# #How many runs to perform using randomly selected hyperparameters
# iterations = 50
# for i in range(iterations):
#     print('iteration number', count)
#     count += 1 #increment count
#     try:
#         d_train = lgb.Dataset(X_train, label=y_train) #Load in data
#         params = {} #initialize parameters
#         params['learning_rate'] = np.random.uniform(0, 1)
#         params['boosting_type'] = np.random.choice(['gbdt', 'dart', 'goss'])
#         params['objective'] = 'regression'
#         params['metric'] = 'mae'
#         params['sub_feature'] = np.random.uniform(0, 1)
#         params['num_leaves'] = np.random.randint(20, 300)
#         params['min_data'] = np.random.randint(10, 100)
#         params['max_depth'] = np.random.randint(5, 200)
#         iterations = np.random.randint(10, 10000)
#         print(params, iterations)
# #Train using selected parameters
#         clf = lgb.train(params, d_train, iterations)
#         y_pred=clf.predict(x_test) #Create predictions on test set
#         mae=mean_absolute_error(y_pred,y_test)
#         print('MAE:', mae)
#         if mae < min:
#             min = mae
#             pp = params 
#     except: #in case something goes wrong
#         print('failed with')
#         print(params)
# print("*" * 50)
# print('Minimum is: ', min)
# print('Used params', pp)

In [50]:
# #=======================================================================================
# # Hyperparameter Grid Search with  
# #=======================================================================================
# from sklearn.model_selection import GridSearchCV
# model_CBR = CatBoostRegressor()
# parameters = {'depth'         : [6,8,10],
#                   'learning_rate' : [0.01, 0.05, 0.1],
#                   'iterations'    : [30, 50, 100]
#                  }
# grid = GridSearchCV(estimator=model_CBR, param_grid = parameters, cv = 2, n_jobs=-1)
# grid.fit(X_train, y_train)
# print(" Results from Grid Search " )
# print("\n The best estimator across ALL searched params:\n", grid.best_estimator_)
# print("\n The best score across ALL searched params:\n", grid.best_score_)
# print("\n The best parameters across ALL searched params:\n", grid.best_params_)

# Machine Learning Models

In [51]:
models ={
           
             #'XGBR': XGBRegressor(base_score=0.5, booster="gbtree", colsample_bylevel=1,
#                        colsample_bynode=1, colsample_bytree=1, gamma=0,
#                        importance_type="gain", learning_rate=0.1, max_delta_step=0,
#                        max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
#                        n_jobs=1, nthread=None, objective="reg:linear", random_state=0,
#                        reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
#                        silent=None, subsample=1, verbosity=1),
             # 'regr': RandomForestRegressor(max_depth=2, random_state=0)
    

             #'gbm':lgb.LGBMRegressor(num_leaves=50,learning_rate=0.05,n_estimators=20),
            'cb':CatBoostRegressor(depth=16, iterations=100, learning_rate=0.1)
}

In [52]:
for name,model in models.items():
    print(f'Using model:{name}')
    model.fit(X_train, y_train)
    print(f'Training Score :{model.score(X_train, y_train)}')
    print(f'Test Score :{model.score(X_test, y_test)}')
    y_pred=model.predict(X_test)
    print(f'MSE:{mean_squared_error(y_test,y_pred)}')
    print(f'RMSE:{np.sqrt(mean_squared_error (y_test,y_pred)) }')
    #print(f'r2_score :{r2_score(y_test, y_pred)}')

    print('=====================================================')

Using model:cb
0:	learn: 57.3169818	total: 1.09s	remaining: 1m 48s
1:	learn: 55.5692556	total: 2.02s	remaining: 1m 38s
2:	learn: 54.1778547	total: 2.93s	remaining: 1m 34s
3:	learn: 52.8199498	total: 3.84s	remaining: 1m 32s
4:	learn: 51.6218641	total: 4.73s	remaining: 1m 29s
5:	learn: 50.6112598	total: 5.61s	remaining: 1m 27s
6:	learn: 49.7215230	total: 6.53s	remaining: 1m 26s
7:	learn: 48.9357800	total: 7.45s	remaining: 1m 25s
8:	learn: 48.2199774	total: 8.39s	remaining: 1m 24s
9:	learn: 47.5603128	total: 9.29s	remaining: 1m 23s
10:	learn: 46.9482528	total: 10.2s	remaining: 1m 22s
11:	learn: 46.4439179	total: 11.1s	remaining: 1m 21s
12:	learn: 45.9766105	total: 12s	remaining: 1m 20s
13:	learn: 45.5875593	total: 12.9s	remaining: 1m 19s
14:	learn: 45.2218938	total: 13.8s	remaining: 1m 18s
15:	learn: 44.9084911	total: 14.8s	remaining: 1m 17s
16:	learn: 44.5834663	total: 15.7s	remaining: 1m 16s
17:	learn: 44.3015695	total: 16.7s	remaining: 1m 15s
18:	learn: 44.0353998	total: 17.6s	remaining: 1m 15s
19:	learn: 43.7384136	total: 18.6s	remaining: 1m 14s
20:	learn: 43.4976492	total: 19.5s	remaining: 1m 13s
21:	learn: 43.2778204	total: 20.5s	remaining: 1m 12s
22:	learn: 43.0942116	total: 21.4s	remaining: 1m 11s
23:	learn: 42.8609221	total: 22.4s	remaining: 1m 10s
24:	learn: 42.6998030	total: 23.4s	remaining: 1m 10s
25:	learn: 42.5213070	total: 24.3s	remaining: 1m 9s
26:	learn: 42.3473803	total: 25.3s	remaining: 1m 8s
27:	learn: 42.1981127	total: 26.3s	remaining: 1m 7s
28:	learn: 42.0501493	total: 27.2s	remaining: 1m 6s
29:	learn: 41.9096165	total: 28.1s	remaining: 1m 5s
30:	learn: 41.7372684	total: 29.1s	remaining: 1m 4s
31:	learn: 41.6078171	total: 30s	remaining: 1m 3s
32:	learn: 41.4794162	total: 31s	remaining: 1m 2s
33:	learn: 41.3271585	total: 31.9s	remaining: 1m 2s
34:	learn: 41.1668004	total: 32.9s	remaining: 1m 1s
35:	learn: 41.0552030	total: 33.9s	remaining: 1m
36:	learn: 40.9407570	total: 34.8s	remaining: 59.2s
37:	learn: 40.8127079	total: 35.7s	remaining: 58.3s
38:	learn: 40.6814535	total: 36.6s	remaining: 57.2s
39:	learn: 40.5381225	total: 37.5s	remaining: 56.3s
40:	learn: 40.4092390	total: 38.5s	remaining: 55.4s
41:	learn: 40.3195272	total: 39.4s	remaining: 54.4s
42:	learn: 40.2055760	total: 40.4s	remaining: 53.5s
43:	learn: 40.1327434	total: 41.4s	remaining: 52.6s
44:	learn: 40.0421902	total: 42.2s	remaining: 51.6s
45:	learn: 39.9490414	total: 43.1s	remaining: 50.7s
46:	learn: 39.8399839	total: 44s	remaining: 49.6s
47:	learn: 39.7544503	total: 44.9s	remaining: 48.7s
48:	learn: 39.6821144	total: 45.9s	remaining: 47.7s
49:	learn: 39.6188289	total: 46.8s	remaining: 46.8s
50:	learn: 39.4993941	total: 47.7s	remaining: 45.8s
51:	learn: 39.4225387	total: 48.7s	remaining: 44.9s
52:	learn: 39.3596702	total: 49.6s	remaining: 44s
53:	learn: 39.3396682	total: 49.7s	remaining: 42.3s
54:	learn: 39.2714819	total: 50.6s	remaining: 41.4s
55:	learn: 39.1754388	total: 51.6s	remaining: 40.5s
56:	learn: 39.1093344	total: 52.4s	remaining: 39.6s
57:	learn: 39.0033576	total: 53.3s	remaining: 38.6s
58:	learn: 38.9321858	total: 54.2s	remaining: 37.7s
59:	learn: 38.8614840	total: 55.1s	remaining: 36.7s
60:	learn: 38.8072408	total: 56s	remaining: 35.8s
61:	learn: 38.7635771	total: 56.9s	remaining: 34.9s
62:	learn: 38.7018749	total: 57.8s	remaining: 33.9s
63:	learn: 38.6194242	total: 58.6s	remaining: 33s
64:	learn: 38.5513345	total: 59.5s	remaining: 32s
65:	learn: 38.4868513	total: 1m	remaining: 31.1s
66:	learn: 38.4154089	total: 1m 1s	remaining: 30.2s
67:	learn: 38.3505439	total: 1m 2s	remaining: 29.3s
68:	learn: 38.2741881	total: 1m 3s	remaining: 28.4s
69:	learn: 38.2163908	total: 1m 4s	remaining: 27.5s
70:	learn: 38.1595340	total: 1m 5s	remaining: 26.6s
71:	learn: 38.1019085	total: 1m 5s	remaining: 25.6s
72:	learn: 38.0391878	total: 1m 6s	remaining: 24.7s
73:	learn: 37.9726527	total: 1m 7s	remaining: 23.8s
74:	learn: 37.9043998	total: 1m 8s	remaining: 22.9s
75:	learn: 37.8483392	total: 1m 9s	remaining: 22s
76:	learn: 37.7992033	total: 1m 10s	remaining: 21s
77:	learn: 37.7331194	total: 1m 11s	remaining: 20.1s
78:	learn: 37.6537783	total: 1m 12s	remaining: 19.2s
79:	learn: 37.6046089	total: 1m 13s	remaining: 18.3s
80:	learn: 37.5388645	total: 1m 14s	remaining: 17.4s
81:	learn: 37.4614318	total: 1m 14s	remaining: 16.5s
82:	learn: 37.4138138	total: 1m 15s	remaining: 15.5s
83:	learn: 37.3614963	total: 1m 16s	remaining: 14.6s
84:	learn: 37.3081373	total: 1m 17s	remaining: 13.7s
85:	learn: 37.2238444	total: 1m 18s	remaining: 12.8s
86:	learn: 37.1864699	total: 1m 19s	remaining: 11.9s
87:	learn: 37.1310833	total: 1m 20s	remaining: 10.9s
88:	learn: 37.0684495	total: 1m 21s	remaining: 10s
89:	learn: 37.0068296	total: 1m 22s	remaining: 9.12s
90:	learn: 36.9680826	total: 1m 23s	remaining: 8.21s
91:	learn: 36.9074540	total: 1m 23s	remaining: 7.3s
92:	learn: 36.8534451	total: 1m 24s	remaining: 6.39s
93:	learn: 36.8033681	total: 1m 25s	remaining: 5.47s
94:	learn: 36.7457366	total: 1m 26s	remaining: 4.56s
95:	learn: 36.7205856	total: 1m 27s	remaining: 3.65s
96:	learn: 36.6778382	total: 1m 28s	remaining: 2.74s
97:	learn: 36.6118601	total: 1m 29s	remaining: 1.82s
98:	learn: 36.5686654	total: 1m 30s	remaining: 912ms
99:	learn: 36.5196479	total: 1m 31s	remaining: 0us
Training Score :0.6189325733726345
Test Score :0.48331311511165775
MSE:1533.4081911525573
RMSE:39.15875625134891
=====================================================

In [53]:
X.columns

Index(['floor_area', 'year_built', 'energy_star_rating', 'january_min_temp', 'january_avg_temp',
       'june_min_temp', 'september_avg_temp', 'snowdepth_inches', 'State_Factor_State_6',
       'building_class_Residential', 'facility_type_Commercial_Other',
       'facility_type_Education_College_or_university', 'facility_type_Education_Other_classroom',
       'facility_type_Food_Service_Restaurant_or_cafeteria',
       'facility_type_Grocery_store_or_food_market', 'facility_type_Health_Care_Inpatient',
       'facility_type_Health_Care_Outpatient_Uncategorized',
       'facility_type_Health_Care_Uncategorized', 'facility_type_Industrial',
       'facility_type_Laboratory', 'facility_type_Lodging_Hotel',
       'facility_type_Mixed_Use_Commercial_and_Residential',
       'facility_type_Multifamily_Uncategorized', 'facility_type_Nursing_Home',
       'facility_type_Office_Medical_non_diagnostic', 'facility_type_Office_Uncategorized',
       'facility_type_Parking_Garage', 'facility_type_Warehouse_Distribution_or_Shipping_center',
       'facility_type_Warehouse_Nonrefrigerated', 'facility_type_Warehouse_Selfstorage'],
      dtype='object')

In [54]:
import joblib
joblib.dump(model,'model.h5')

['model.h5']

In [55]:
joblib.dump(scaler,'scaler.h5')

['scaler.h5']

# Pipeline

In [56]:
from sklearn.pipeline import Pipeline

In [57]:
steps = [('imputer', SimpleImputer(strategy='median')),
         ('scalar', StandardScaler()),
         ('selector',SelectPercentile(percentile=50, score_func=mutual_info_regression)),
         ('split',train_test_split(X, Y, test_size=0.2, random_state=2))
         ('model', XGBRegressor())]

TypeError: 'tuple' object is not callable

In [ ]:
PipelineModel = Pipeline(steps)
PipelineModel.fit(X_test, y_test)

In [ ]:
X_test